### ISSUE TITLE
Not sure what this error means

### ISSUE THREAD

**Issue by EmperorEarth** [tbranyen/salita#10]
I just tried Salita and got the following error message:
![image](https://cloud.githubusercontent.com/assets/7605016/12561561/dbfce712-c36e-11e5-8853-24a781159a0a.png)

> salita --check
returns the same error, same line numbers, same stack trace

Working Repository/Directory information is redacted, but I don't think it's relevant.
Windows 7x64
NPM v3.5.3
Salita v0.8.5

**Comment by Xotic750** [comment]
Seems to be reading a file named `asap.js` which is a Javascript file, it should be reading `package.json`. which is a JSON file. Do you that file in that directory?

**Comment by ljharb** [comment]
The error is naturally happening inside a promise, but it's likely to do with Windows filesystem stuff. Can you gist the package.json of the project you're running salita on?

**Comment by EmperorEarth** [comment]
User error

I added a comment to my package.json as a compile break/reminder/bookmark.
