### ISSUE TITLE
Should this package make destructive edits by default?

### ISSUE THREAD

**Issue by TomKaltz** [tbranyen/salita#11]
Wondering if actually making changes to package.json should be protected behind a command line flag.  It seems too easy to be destructive just by typing salita.

**Comment by ljharb** [comment]
That seems like a reasonable breaking change.

**Comment by TomKaltz** [comment]
I suggest ```--dry-run``` becoming the default behavior.  That way it works similarly to the non-destructive ```npm outdated```.  Not sure what the new flag should be.  Perhaps ```--update```?

**Comment by tbranyen** [comment]
Agreed, I usually want to dry-run before actually applying.

**Comment by ljharb** [comment]
I'll get to this shortly.

**Comment by ljharb** [comment]
Additional `--update` option added in v0.9.1, swapping the defaults so that `dry-run` is the default will be in `v0.10.0`.
