### ISSUE TITLE
Enhancement: `--pin` (or some option) to change `latest` to actual current version numbers

### ISSUE THREAD

**Issue by Xotic750** [tbranyen/salita#13]
I really like this project. However, often when writing projects, I don't actually look up the current version number of a module and I just set it to `latest`. When I am ready to publish though, I change `latest` to the version number of the module that I have been writing and testing with.

I would like an option like `--pin` that changes all the `latest` values to their current version. I didn't find a way to do this currently with salita? If I haven't missed how it can be currently done, could an option like this be considered?

**Comment by ljharb** [comment]
I really really discourage that approach. That means that, when writing projects, things might break out from under you. Best practice is to always, *always*, use some sort of version, ideally a range with `^`.

Regardless, by default, `*` does get updated by `salita` - but `latest` does not. I'll make sure it treats "latest" and "*" the same.

**Comment by Xotic750** [comment]
That's great. I didn't think of having them treated the same or even trying `*`. I'll avoid that bad practise, thanks.
